import type { Country } from './types'

export const COUNTRIES: Country[] = [
  {
    code: 'GB',
    name: 'United Kingdom',
    flag: '🇬🇧',
    tier: 1,
    complexityLabel: 'Straightforward',
    thresholdNative: 10,
    thresholdNonNative: 14,
    setupCostLow: 20000,
    setupCostHigh: 30000,
    ongoingCostPerEmployeePerYear: 3500,
    setupMonthsLow: 2,
    setupMonthsHigh: 4,
    eorMarketRateMonthly: 599,
    currency: 'GBP',
    complexityFactors: [
      'Common law system — flexible employment contracts',
      'TUPE regulations apply on business transfers',
      'Auto-enrolment pension obligations from day one',
      'IR35 contractor classification rules',
      'Statutory redundancy payment obligations',
    ],
    redFlags: [
      'Do you have contractors who may be inside IR35?',
      'Are you acquiring a UK business (TUPE applies)?',
      'Do you need to hire across England, Scotland, and Wales simultaneously?',
    ],
    languageBufferApplies: false,
  },
  {
    code: 'DE',
    name: 'Germany',
    flag: '🇩🇪',
    tier: 2,
    complexityLabel: 'Moderate',
    thresholdNative: 15,
    thresholdNonNative: 20,
    setupCostLow: 25000,
    setupCostHigh: 40000,
    ongoingCostPerEmployeePerYear: 5000,
    setupMonthsLow: 4,
    setupMonthsHigh: 6,
    eorMarketRateMonthly: 599,
    currency: 'EUR',
    complexityFactors: [
      'Works councils mandatory if requested at 5+ employees',
      'Strong dismissal protection laws (Kündigungsschutzgesetz)',
      'Co-determination rights at 500+ employees',
      'GmbH minimum share capital €25,000',
      'Notarisation required for company formation',
    ],
    redFlags: [
      'Do you already have 5+ employees who may request a works council?',
      'Are any roles subject to collective bargaining agreements?',
      'Do you need to terminate employees — German dismissal law is strict?',
    ],
    languageBufferApplies: true,
  },
  {
    code: 'FR',
    name: 'France',
    flag: '🇫🇷',
    tier: 2,
    complexityLabel: 'Moderate',
    thresholdNative: 15,
    thresholdNonNative: 20,
    setupCostLow: 22000,
    setupCostHigh: 38000,
    ongoingCostPerEmployeePerYear: 4800,
    setupMonthsLow: 3,
    setupMonthsHigh: 6,
    eorMarketRateMonthly: 599,
    currency: 'EUR',
    complexityFactors: [
      'Employee representative body required at 11+ employees',
      'Sector-specific collective agreements (conventions collectives)',
      'Strict rules on working hours and overtime',
      'SAS or SARL — minimum €1 share capital but high admin burden',
      '35-hour working week statutory baseline',
    ],
    redFlags: [
      'Do your roles fall under a sector collective agreement?',
      'Are you planning more than 10 employees — triggering staff representation?',
      'Do you need to manage French payroll in-house?',
    ],
    languageBufferApplies: true,
  },
  {
    code: 'NL',
    name: 'Netherlands',
    flag: '🇳🇱',
    tier: 1,
    complexityLabel: 'Straightforward',
    thresholdNative: 10,
    thresholdNonNative: 13,
    setupCostLow: 18000,
    setupCostHigh: 28000,
    ongoingCostPerEmployeePerYear: 4000,
    setupMonthsLow: 2,
    setupMonthsHigh: 4,
    eorMarketRateMonthly: 599,
    currency: 'EUR',
    complexityFactors: [
      'BV (private limited) — no minimum share capital since 2012',
      'Works council required at 50+ employees',
      '30% ruling available for qualifying expat employees',
      'Notarial deed required for BV incorporation',
      'Strong employee protections via UWV and courts',
    ],
    redFlags: [
      'Do you need to use the 30% tax ruling for international hires?',
      'Are you approaching 50 employees — works council threshold?',
    ],
    languageBufferApplies: false,
  },
  {
    code: 'ES',
    name: 'Spain',
    flag: '🇪🇸',
    tier: 2,
    complexityLabel: 'Moderate',
    thresholdNative: 15,
    thresholdNonNative: 20,
    setupCostLow: 20000,
    setupCostHigh: 35000,
    ongoingCostPerEmployeePerYear: 4200,
    setupMonthsLow: 3,
    setupMonthsHigh: 6,
    eorMarketRateMonthly: 599,
    currency: 'EUR',
    complexityFactors: [
      'SL formation requires notary and Mercantile Registry',
      'Sector collective agreements are legally binding',
      'High employer social security contributions (~29.9%)',
      'Employee committee rights at 50+ employees',
      'Regional employment laws vary (Catalonia, Basque Country)',
    ],
    redFlags: [
      'Are employees in Catalonia or the Basque Country — regional rules apply?',
      'Do roles fall under a collective agreement?',
      'Are you planning redundancies — Spanish severance is significant?',
    ],
    languageBufferApplies: true,
  },
  {
    code: 'IE',
    name: 'Ireland',
    flag: '🇮🇪',
    tier: 1,
    complexityLabel: 'Straightforward',
    thresholdNative: 8,
    thresholdNonNative: 11,
    setupCostLow: 15000,
    setupCostHigh: 25000,
    ongoingCostPerEmployeePerYear: 3200,
    setupMonthsLow: 1,
    setupMonthsHigh: 3,
    eorMarketRateMonthly: 599,
    currency: 'EUR',
    complexityFactors: [
      'Common law system — similar to UK',
      'Low corporate tax rate (12.5% trading income)',
      'Company registration via CRO — straightforward process',
      'EU member — full single market access',
      'GDPR compliance required as EU jurisdiction',
    ],
    redFlags: [
      'Do you need a local director resident in Ireland?',
      'Are you relying on the 12.5% tax rate — substance requirements apply?',
    ],
    languageBufferApplies: false,
  },
  {
    code: 'SE',
    name: 'Sweden',
    flag: '🇸🇪',
    tier: 1,
    complexityLabel: 'Straightforward',
    thresholdNative: 10,
    thresholdNonNative: 13,
    setupCostLow: 18000,
    setupCostHigh: 28000,
    ongoingCostPerEmployeePerYear: 4500,
    setupMonthsLow: 2,
    setupMonthsHigh: 4,
    eorMarketRateMonthly: 599,
    currency: 'SEK',
    complexityFactors: [
      'AB (Aktiebolag) requires SEK 25,000 minimum share capital',
      'Strong union presence — collective agreements common',
      'Co-determination Act gives employees consultation rights',
      'Generous statutory leave entitlements (25 days minimum)',
      'Employer social contributions ~31.4%',
    ],
    redFlags: [
      'Are employees unionised or in sectors with collective agreements?',
      'Do you need to consult unions before making significant changes?',
    ],
    languageBufferApplies: false,
  },
  {
    code: 'DK',
    name: 'Denmark',
    flag: '🇩🇰',
    tier: 1,
    complexityLabel: 'Straightforward',
    thresholdNative: 10,
    thresholdNonNative: 13,
    setupCostLow: 17000,
    setupCostHigh: 27000,
    ongoingCostPerEmployeePerYear: 4200,
    setupMonthsLow: 2,
    setupMonthsHigh: 3,
    eorMarketRateMonthly: 599,
    currency: 'DKK',
    complexityFactors: [
      'ApS requires DKK 40,000 minimum share capital',
      'Flexicurity model — easy to hire and fire but strong social safety net',
      'Collective agreements cover ~70% of workforce',
      'High income tax but low employer social contributions',
      'Danish Business Authority registration — efficient process',
    ],
    redFlags: [
      'Are roles covered by Danish collective agreements?',
      'Do you need to register for Danish VAT immediately?',
    ],
    languageBufferApplies: false,
  },
  {
    code: 'NO',
    name: 'Norway',
    flag: '🇳🇴',
    tier: 1,
    complexityLabel: 'Straightforward',
    thresholdNative: 10,
    thresholdNonNative: 13,
    setupCostLow: 18000,
    setupCostHigh: 28000,
    ongoingCostPerEmployeePerYear: 4500,
    setupMonthsLow: 2,
    setupMonthsHigh: 4,
    eorMarketRateMonthly: 599,
    currency: 'NOK',
    complexityFactors: [
      'AS requires NOK 30,000 minimum share capital',
      'Working Environment Act — strong employee protections',
      'Employer NIC varies by region (0–14.1%)',
      'Non-EU — EEA agreements apply',
      'Mandatory occupational pension contributions',
    ],
    redFlags: [
      'Are you hiring in high-NIC regions (Oslo vs northern Norway)?',
      'Do employees need Norwegian-language contracts?',
    ],
    languageBufferApplies: true,
  },
  {
    code: 'FI',
    name: 'Finland',
    flag: '🇫🇮',
    tier: 1,
    complexityLabel: 'Straightforward',
    thresholdNative: 10,
    thresholdNonNative: 14,
    setupCostLow: 16000,
    setupCostHigh: 26000,
    ongoingCostPerEmployeePerYear: 4000,
    setupMonthsLow: 2,
    setupMonthsHigh: 4,
    eorMarketRateMonthly: 599,
    currency: 'EUR',
    complexityFactors: [
      'OY (Osakeyhtiö) — no minimum share capital since 2019',
      'Collective agreements are sector-wide and legally binding',
      'Co-operation Act — mandatory consultation at 20+ employees',
      'Strong data protection culture — GDPR strictly enforced',
      'Bilingual country — Swedish is co-official language',
    ],
    redFlags: [
      'Do you need Swedish-language documentation for Finnish-Swedish employees?',
      'Are you approaching 20 employees — co-operation consultation triggers?',
    ],
    languageBufferApplies: true,
  },
  {
    code: 'BE',
    name: 'Belgium',
    flag: '🇧🇪',
    tier: 2,
    complexityLabel: 'Moderate',
    thresholdNative: 12,
    thresholdNonNative: 16,
    setupCostLow: 22000,
    setupCostHigh: 36000,
    ongoingCostPerEmployeePerYear: 4800,
    setupMonthsLow: 3,
    setupMonthsHigh: 5,
    eorMarketRateMonthly: 599,
    currency: 'EUR',
    complexityFactors: [
      'Three official languages — French, Dutch, German — affect contracts',
      'Regional employment law differences (Flanders, Wallonia, Brussels)',
      'High employer social security contributions (~25%)',
      'Joint committees (paritaire comités) govern sector-level pay',
      'Mandatory indexation of salaries',
    ],
    redFlags: [
      'Are employees in different regions — Flemish vs Walloon rules differ?',
      'Does your sector have a joint committee with mandatory pay scales?',
      'Do you need trilingual HR documentation?',
    ],
    languageBufferApplies: true,
  },
  {
    code: 'CH',
    name: 'Switzerland',
    flag: '🇨🇭',
    tier: 2,
    complexityLabel: 'Moderate',
    thresholdNative: 12,
    thresholdNonNative: 16,
    setupCostLow: 30000,
    setupCostHigh: 50000,
    ongoingCostPerEmployeePerYear: 6000,
    setupMonthsLow: 3,
    setupMonthsHigh: 5,
    eorMarketRateMonthly: 699,
    currency: 'CHF',
    complexityFactors: [
      'GmbH requires CHF 20,000 minimum share capital',
      'Four official languages — German, French, Italian, Romansh',
      'Non-EU — bilateral agreements with EU',
      'Cantonal differences in tax and registration',
      'High cost base but low corporate tax in many cantons',
    ],
    redFlags: [
      'Which canton are you registering in — tax rates vary significantly?',
      'Do you need work permits for non-Swiss/EU employees?',
      'Are salaries subject to cantonal minimum wage rules?',
    ],
    languageBufferApplies: true,
  },
  {
    code: 'AT',
    name: 'Austria',
    flag: '🇦🇹',
    tier: 2,
    complexityLabel: 'Moderate',
    thresholdNative: 12,
    thresholdNonNative: 16,
    setupCostLow: 22000,
    setupCostHigh: 35000,
    ongoingCostPerEmployeePerYear: 4600,
    setupMonthsLow: 3,
    setupMonthsHigh: 5,
    eorMarketRateMonthly: 599,
    currency: 'EUR',
    complexityFactors: [
      'GmbH requires €35,000 minimum share capital',
      'Works councils at 5+ employees if requested',
      'Collective agreements (Kollektivverträge) cover most sectors',
      'Mandatory severance fund contributions from day one',
      'Social partner system — unions and employers negotiate centrally',
    ],
    redFlags: [
      'Does your sector have a collective agreement with mandatory pay grades?',
      'Are you aware of mandatory Abfertigung (severance fund) contributions?',
    ],
    languageBufferApplies: true,
  },
  {
    code: 'PT',
    name: 'Portugal',
    flag: '🇵🇹',
    tier: 2,
    complexityLabel: 'Moderate',
    thresholdNative: 13,
    thresholdNonNative: 17,
    setupCostLow: 18000,
    setupCostHigh: 30000,
    ongoingCostPerEmployeePerYear: 3800,
    setupMonthsLow: 3,
    setupMonthsHigh: 5,
    eorMarketRateMonthly: 599,
    currency: 'EUR',
    complexityFactors: [
      'Lda (Limitada) formation — relatively straightforward',
      'NHR (Non-Habitual Resident) regime attractive for international hires',
      'Mandatory 22 days annual leave plus 13 public holidays',
      'Employer social security contributions ~23.75%',
      'Strong unfair dismissal protections',
    ],
    redFlags: [
      'Are you hiring NHR-eligible international employees?',
      'Do you plan redundancies — Portuguese dismissal law is restrictive?',
    ],
    languageBufferApplies: false,
  },
  {
    code: 'IT',
    name: 'Italy',
    flag: '🇮🇹',
    tier: 3,
    complexityLabel: 'Complex',
    thresholdNative: 20,
    thresholdNonNative: 25,
    setupCostLow: 30000,
    setupCostHigh: 50000,
    ongoingCostPerEmployeePerYear: 6000,
    setupMonthsLow: 5,
    setupMonthsHigh: 8,
    eorMarketRateMonthly: 699,
    currency: 'EUR',
    complexityFactors: [
      'SRL requires €10,000 minimum share capital',
      'National collective agreements (CCNL) are binding by sector',
      'TFR (Trattamento Fine Rapporto) — mandatory severance accrual',
      'Notarial deed required — bureaucratic process',
      'Regional labour courts frequently involved in disputes',
    ],
    redFlags: [
      'Which CCNL applies to your sector — pay scales and entitlements vary widely?',
      'Are you aware of mandatory TFR accrual obligations?',
      'Do you have Italian-speaking HR/legal support?',
    ],
    languageBufferApplies: true,
  },
  {
    code: 'PL',
    name: 'Poland',
    flag: '🇵🇱',
    tier: 2,
    complexityLabel: 'Moderate',
    thresholdNative: 14,
    thresholdNonNative: 18,
    setupCostLow: 15000,
    setupCostHigh: 25000,
    ongoingCostPerEmployeePerYear: 3000,
    setupMonthsLow: 3,
    setupMonthsHigh: 5,
    eorMarketRateMonthly: 599,
    currency: 'PLN',
    complexityFactors: [
      'sp. z o.o. — PLN 5,000 minimum share capital',
      'Works councils and trade unions have consultation rights',
      'Social insurance contributions split employer/employee',
      'Polish Labour Code — comprehensive employee protections',
      'KRS (National Court Register) — registration required',
    ],
    redFlags: [
      'Do you need Polish-language employment contracts?',
      'Are any employees trade union members — consultation obligations?',
    ],
    languageBufferApplies: true,
  },
  {
    code: 'CZ',
    name: 'Czech Republic',
    flag: '🇨🇿',
    tier: 2,
    complexityLabel: 'Moderate',
    thresholdNative: 13,
    thresholdNonNative: 17,
    setupCostLow: 14000,
    setupCostHigh: 24000,
    ongoingCostPerEmployeePerYear: 2800,
    setupMonthsLow: 3,
    setupMonthsHigh: 5,
    eorMarketRateMonthly: 599,
    currency: 'CZK',
    complexityFactors: [
      's.r.o. — CZK 1 minimum share capital (practically higher)',
      'Labour Code governs employment — notice periods 1–3 months',
      'Employer social and health insurance contributions ~34%',
      'Works councils at 25+ employees',
      'Czech-language contracts required',
    ],
    redFlags: [
      'Do you need Czech-language employment documentation?',
      'Are you approaching 25 employees — works council threshold?',
    ],
    languageBufferApplies: true,
  },
  {
    code: 'RO',
    name: 'Romania',
    flag: '🇷🇴',
    tier: 2,
    complexityLabel: 'Moderate',
    thresholdNative: 13,
    thresholdNonNative: 17,
    setupCostLow: 12000,
    setupCostHigh: 20000,
    ongoingCostPerEmployeePerYear: 2500,
    setupMonthsLow: 3,
    setupMonthsHigh: 5,
    eorMarketRateMonthly: 599,
    currency: 'RON',
    complexityFactors: [
      'SRL — RON 200 minimum share capital',
      'Labour Code — comprehensive, employee-protective',
      'REVISAL — mandatory electronic labour register',
      'High employer social contributions (~20.5%)',
      'Romanian-language contracts required',
    ],
    redFlags: [
      'Are you registered in REVISAL (mandatory labour registry)?',
      'Do you need Romanian-language HR documentation?',
    ],
    languageBufferApplies: true,
  },
  {
    code: 'HU',
    name: 'Hungary',
    flag: '🇭🇺',
    tier: 2,
    complexityLabel: 'Moderate',
    thresholdNative: 13,
    thresholdNonNative: 17,
    setupCostLow: 13000,
    setupCostHigh: 22000,
    ongoingCostPerEmployeePerYear: 2700,
    setupMonthsLow: 3,
    setupMonthsHigh: 5,
    eorMarketRateMonthly: 599,
    currency: 'HUF',
    complexityFactors: [
      'Kft — HUF 3,000,000 minimum share capital (~€8k)',
      'Labour Code 2012 — relatively employer-friendly vs Western Europe',
      'Works councils at 50+ employees',
      'Hungarian-language contracts required',
      'Social contribution tax ~13% employer side',
    ],
    redFlags: [
      'Do you need Hungarian-language employment contracts?',
      'Are you planning to use the flat 9% corporate tax rate — substance required?',
    ],
    languageBufferApplies: true,
  },
  {
    code: 'GR',
    name: 'Greece',
    flag: '🇬🇷',
    tier: 3,
    complexityLabel: 'Complex',
    thresholdNative: 18,
    thresholdNonNative: 23,
    setupCostLow: 22000,
    setupCostHigh: 38000,
    ongoingCostPerEmployeePerYear: 4000,
    setupMonthsLow: 5,
    setupMonthsHigh: 9,
    eorMarketRateMonthly: 699,
    currency: 'EUR',
    complexityFactors: [
      'IKE or EPE — different capital requirements',
      'ERGANI system — mandatory employment notifications',
      'Collective agreements via GSEE and sector unions',
      'Bureaucratic registration process — notarial involvement',
      'EFKA social security — complex contribution structure',
    ],
    redFlags: [
      'Are you registered with ERGANI for employee notifications?',
      'Do you have local legal support for Greek bureaucracy?',
    ],
    languageBufferApplies: true,
  },
  {
    code: 'US',
    name: 'United States',
    flag: '🇺🇸',
    tier: 3,
    complexityLabel: 'Complex',
    thresholdNative: 20,
    thresholdNonNative: 25,
    setupCostLow: 35000,
    setupCostHigh: 60000,
    ongoingCostPerEmployeePerYear: 6500,
    setupMonthsLow: 3,
    setupMonthsHigh: 6,
    eorMarketRateMonthly: 599,
    currency: 'USD',
    complexityFactors: [
      'State-by-state registration — each state where employees work requires entity registration',
      'Federal + state + local employment law layering',
      'Benefits administration — health insurance is employer-managed',
      'At-will employment varies by state exceptions',
      'FUTA, SUTA, FICA — multi-layer payroll tax obligations',
    ],
    redFlags: [
      'Do you have employees in multiple states — each requires separate registration?',
      'Are you offering health insurance — this is a major cost and admin burden?',
      'Do any states you operate in have salary transparency laws?',
    ],
    languageBufferApplies: false,
  },
  {
    code: 'CA',
    name: 'Canada',
    flag: '🇨🇦',
    tier: 2,
    complexityLabel: 'Moderate',
    thresholdNative: 15,
    thresholdNonNative: 19,
    setupCostLow: 25000,
    setupCostHigh: 42000,
    ongoingCostPerEmployeePerYear: 5500,
    setupMonthsLow: 3,
    setupMonthsHigh: 5,
    eorMarketRateMonthly: 599,
    currency: 'CAD',
    complexityFactors: [
      'Federal vs provincial employment law — province governs most employment',
      'Quebec distinct legal system (civil law, French language)',
      'CPP, EI, provincial health levies — multi-layer payroll',
      'Pay equity legislation in Ontario and federally regulated sectors',
      'Corporation registration federally or provincially',
    ],
    redFlags: [
      'Do you have employees in Quebec — separate French-language requirements?',
      'Are you federally regulated (banking, telecoms, aviation) — different rules?',
    ],
    languageBufferApplies: false,
  },
  {
    code: 'AU',
    name: 'Australia',
    flag: '🇦🇺',
    tier: 2,
    complexityLabel: 'Moderate',
    thresholdNative: 12,
    thresholdNonNative: 16,
    setupCostLow: 20000,
    setupCostHigh: 35000,
    ongoingCostPerEmployeePerYear: 5000,
    setupMonthsLow: 2,
    setupMonthsHigh: 4,
    eorMarketRateMonthly: 599,
    currency: 'AUD',
    complexityFactors: [
      'Pty Ltd — straightforward ASIC registration',
      'Fair Work Act — National Employment Standards apply',
      'Superannuation — mandatory 11% employer contribution',
      'Modern Awards cover most industries — minimum pay rates',
      'State-based workers compensation and payroll tax thresholds',
    ],
    redFlags: [
      'Do you know which Modern Award applies to your employees?',
      'Are you registered for superannuation contributions?',
      'Do you have employees in multiple states — payroll tax thresholds vary?',
    ],
    languageBufferApplies: false,
  },
  {
    code: 'NZ',
    name: 'New Zealand',
    flag: '🇳🇿',
    tier: 1,
    complexityLabel: 'Straightforward',
    thresholdNative: 10,
    thresholdNonNative: 13,
    setupCostLow: 16000,
    setupCostHigh: 26000,
    ongoingCostPerEmployeePerYear: 4000,
    setupMonthsLow: 1,
    setupMonthsHigh: 3,
    eorMarketRateMonthly: 599,
    currency: 'NZD',
    complexityFactors: [
      'Companies Act 1993 — simple registration via Companies Office',
      'Employment Relations Act — good faith obligation',
      'KiwiSaver — 3% minimum employer contribution',
      'No-fault accident compensation (ACC) — employer levies apply',
      'Relatively straightforward employment law',
    ],
    redFlags: [
      'Are you registered for ACC employer levies?',
      'Do employment agreements meet the Employment Relations Act good faith requirements?',
    ],
    languageBufferApplies: false,
  },
  {
    code: 'SG',
    name: 'Singapore',
    flag: '🇸🇬',
    tier: 1,
    complexityLabel: 'Straightforward',
    thresholdNative: 8,
    thresholdNonNative: 10,
    setupCostLow: 15000,
    setupCostHigh: 25000,
    ongoingCostPerEmployeePerYear: 3500,
    setupMonthsLow: 1,
    setupMonthsHigh: 2,
    eorMarketRateMonthly: 599,
    currency: 'SGD',
    complexityFactors: [
      'Pte Ltd — fast ACRA registration (1–3 days)',
      'Employment Act — applies to most employees earning under SGD 2,600/month',
      'CPF contributions — employer 17%, employee 20%',
      'EP, S Pass, Work Permit — quota system for foreign hiring',
      'Low corporate tax rate (17%) with exemptions',
    ],
    redFlags: [
      'Do you need EP or S Pass for foreign employees — quota rules apply?',
      'Are you aware of Fair Consideration Framework for local hiring?',
    ],
    languageBufferApplies: false,
  },
  {
    code: 'JP',
    name: 'Japan',
    flag: '🇯🇵',
    tier: 3,
    complexityLabel: 'Complex',
    thresholdNative: 20,
    thresholdNonNative: 25,
    setupCostLow: 40000,
    setupCostHigh: 65000,
    ongoingCostPerEmployeePerYear: 7000,
    setupMonthsLow: 6,
    setupMonthsHigh: 12,
    eorMarketRateMonthly: 699,
    currency: 'JPY',
    complexityFactors: [
      'KK (Kabushiki Kaisha) — ¥1 minimum capital but significant setup complexity',
      'Employment security law — very strong protections against dismissal',
      'Social insurance — kenpo, kosei nenkin, employment insurance',
      'Work rules (Shūgyō Kisoku) required at 10+ employees',
      'Japanese-language documentation required throughout',
    ],
    redFlags: [
      'Do you have Japanese-speaking HR/legal support?',
      'Are you planning terminations — Japanese dismissal law is among the strictest globally?',
      'Are work rules (Shūgyō Kisoku) filed with the Labour Standards Office?',
    ],
    languageBufferApplies: true,
  },
  {
    code: 'IN',
    name: 'India',
    flag: '🇮🇳',
    tier: 3,
    complexityLabel: 'Complex',
    thresholdNative: 20,
    thresholdNonNative: 25,
    setupCostLow: 20000,
    setupCostHigh: 40000,
    ongoingCostPerEmployeePerYear: 4000,
    setupMonthsLow: 4,
    setupMonthsHigh: 8,
    eorMarketRateMonthly: 599,
    currency: 'INR',
    complexityFactors: [
      'Private Limited — MCA registration, DSC, DIN required',
      'State-by-state labour law variation (Shops and Establishment Acts)',
      'PF, ESI, PT, LWF — multiple statutory contribution layers',
      'Labour codes consolidation underway but implementation varies by state',
      'Shop and Establishment registration in each operating state',
    ],
    redFlags: [
      'Do you have employees in multiple states — each requires separate registration?',
      'Are you registered for PF and ESI contributions?',
      'Do you need a local director who is Indian resident?',
    ],
    languageBufferApplies: false,
  },
  {
    code: 'BR',
    name: 'Brazil',
    flag: '🇧🇷',
    tier: 3,
    complexityLabel: 'Complex',
    thresholdNative: 20,
    thresholdNonNative: 25,
    setupCostLow: 30000,
    setupCostHigh: 55000,
    ongoingCostPerEmployeePerYear: 6500,
    setupMonthsLow: 6,
    setupMonthsHigh: 12,
    eorMarketRateMonthly: 699,
    currency: 'BRL',
    complexityFactors: [
      "Ltda or S.A. — CNPJ registration, complex process",
      "CLT (Consolidação das Leis do Trabalho) — one of world's most complex labour codes",
      'FGTS, INSS, IRRF — mandatory fund and contribution layers',
      '13th salary (Décimo Terceiro) and vacation bonus mandatory',
      'eSocial — mandatory digital employment registry',
    ],
    redFlags: [
      'Do you have Brazilian-Portuguese speaking legal support?',
      'Are you aware of 13th salary and mandatory vacation bonus obligations?',
      'Is eSocial registration in place?',
    ],
    languageBufferApplies: true,
  },
  {
    code: 'MX',
    name: 'Mexico',
    flag: '🇲🇽',
    tier: 3,
    complexityLabel: 'Complex',
    thresholdNative: 18,
    thresholdNonNative: 23,
    setupCostLow: 22000,
    setupCostHigh: 40000,
    ongoingCostPerEmployeePerYear: 5000,
    setupMonthsLow: 4,
    setupMonthsHigh: 7,
    eorMarketRateMonthly: 699,
    currency: 'MXN',
    complexityFactors: [
      'S. de R.L. de C.V. — notarial process, SAT registration',
      'IMSS, INFONAVIT, SAR — mandatory social contributions',
      'Profit-sharing (PTU) — 10% of taxable profit distributed to employees',
      'Christmas bonus (Aguinaldo) — minimum 15 days salary',
      'Labour subcontracting reform 2021 — insourcing requirements',
    ],
    redFlags: [
      'Are you aware of PTU (profit sharing) obligations?',
      'Have you reviewed the 2021 labour subcontracting reform impact?',
      'Do you need Spanish-speaking HR/legal support?',
    ],
    languageBufferApplies: true,
  },
  {
    code: 'ZA',
    name: 'South Africa',
    flag: '🇿🇦',
    tier: 2,
    complexityLabel: 'Moderate',
    thresholdNative: 14,
    thresholdNonNative: 18,
    setupCostLow: 16000,
    setupCostHigh: 28000,
    ongoingCostPerEmployeePerYear: 3500,
    setupMonthsLow: 3,
    setupMonthsHigh: 6,
    eorMarketRateMonthly: 599,
    currency: 'ZAR',
    complexityFactors: [
      'Pty Ltd — CIPC registration',
      'Labour Relations Act and BCEA — strong employee protections',
      'B-BBEE compliance considerations for government contracts',
      'UIF, SDL — mandatory contributions',
      'CCMA — Commission for Conciliation, Mediation and Arbitration for disputes',
    ],
    redFlags: [
      'Do you need B-BBEE compliance for government or large corporate contracts?',
      'Are you prepared for CCMA dispute resolution processes?',
    ],
    languageBufferApplies: false,
  },
  {
    code: 'AE',
    name: 'UAE',
    flag: '🇦🇪',
    tier: 2,
    complexityLabel: 'Moderate',
    thresholdNative: 12,
    thresholdNonNative: 15,
    setupCostLow: 25000,
    setupCostHigh: 45000,
    ongoingCostPerEmployeePerYear: 4500,
    setupMonthsLow: 2,
    setupMonthsHigh: 5,
    eorMarketRateMonthly: 699,
    currency: 'AED',
    complexityFactors: [
      'Mainland vs Free Zone — different ownership and operational rules',
      'GRATUITY — mandatory end-of-service benefit accrual',
      'MOHRE registration for mainland entities',
      'WPS (Wage Protection System) — mandatory salary via approved banks',
      'Emiratisation (Nafis) — quota requirements for UAE nationals',
    ],
    redFlags: [
      'Are you setting up mainland or Free Zone — this fundamentally changes the rules?',
      'Are you subject to Emiratisation quotas?',
      'Is WPS (Wage Protection System) compliance in place?',
    ],
    languageBufferApplies: false,
  },
  {
    code: 'KE',
    name: 'Kenya',
    flag: '🇰🇪',
    tier: 2,
    complexityLabel: 'Moderate',
    thresholdNative: 13,
    thresholdNonNative: 17,
    setupCostLow: 14000,
    setupCostHigh: 24000,
    ongoingCostPerEmployeePerYear: 3000,
    setupMonthsLow: 3,
    setupMonthsHigh: 6,
    eorMarketRateMonthly: 599,
    currency: 'KES',
    complexityFactors: [
      'Limited Company — BRS (Business Registration Service) registration',
      'Employment Act 2007 — governs all employment',
      'NSSF, NHIF, PAYE — mandatory statutory deductions',
      'NITA levy for training',
      'eTIMS for tax compliance',
    ],
    redFlags: [
      'Are NSSF and NHIF contributions correctly set up?',
      'Do you need county-specific business permits?',
    ],
    languageBufferApplies: false,
  },
]
